# Generated by Django 5.0.1 on 2025-02-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='fullname',
        ),
    ]
